Feat/keyp 269 remote se server plugin
eclipse/keyple-java pull request #406
Opened 2020-09-09 10:09 UTC by odelcroi

2020-09-10 12:57 UTC, odelcroi commented
retest this please

2020-09-10 13:48 UTC, andrei-cristea requested changes

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerUtils.java
> +/** Utils class to access the @{@link RemoteSeServerPlugin} */
erreur de javadoc @{@...
De plus, cette classe publique devrait être très très bien documentée.

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerUtils.java
> +   * @throws KeyplePluginNotFoundException if no RemoteSeServerPlugin is registered
Ajouter les @since partout

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * Notify event to the master reader observers
garder le {@inheritDoc} et ne peut perturber l'utilisateur avec la notion de "master" reader qui doit être complètement transparente pour lui.

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * @param event non nullable instance of a readerEvent
du coup, supprimer le @param

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * Add observer on the master reader
idem

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * Remove observers on the master reader. If the master reader has no observer left, unplug it
idem

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * Clear observers on the master reader and unplug it from the plugin
idem

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * Count observers on the master reader
idem

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/ServerVirtualObservableReader.java
> +   * @return boolean
mauvais type de retour.

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +   * default name of the RemoteSeServerPlugin for a sync node {@value "RemoteSeServerPluginSync"}
{@value} s'utilise sans paramètre car la valeur est récupérée automatiquement.

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +   * default name of the RemoteSeServerPlugin for a async node {@value "RemoteSeServerPluginAsync"}
idem

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +  public static final String PLUGIN_NAME_SYNC = "RemoteSeServerPluginSync";
La visibilité doit être package-private pour ne pas laissé l'utilisateur avoir accès à cette information. Il doit uniquement utiliser les classes utilitaires.

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +  public static final String PLUGIN_NAME_ASYNC = "RemoteSeServerPluginAsync";
idem

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +  public ReaderPlugin getPlugin() {
Pour respecter le pattern factory, le type de retour doit être un RemoteSeServerPlugin

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +     * @param observer
il faut enrichir la javadoc

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +    BuilderStep withDefaultPool();
Respecter le nommage des diagrammes... usingDefaultEventNotificationPool()

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginFactory.java
> +    BuilderStep withPool(ExecutorService eventNotificationPool);
idem... usingEventNotitificationPool

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +  protected ConcurrentMap<String, SeReader> initNativeReaders() throws KeypleReaderIOException {
La signature peut-être juste une Map

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +  static void unregisterReader(String pluginName, String readerName) {
Pourquoi cette méthode ? Et aussi pourquoi renseigner un pluginName qui n'est pas soit-même ?

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +    Assert.getInstance().notNull(message, "message");
Pas besoin du assert car cette méthode n'est pas publique et n'est pas appelée par l'utilisateur, mais par le node qui a déjà vérifier cela.

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +        ServerVirtualObservableReader delegateVirtualReader = createDelegatedReader(message);
Tant qu'à faire pour rester cohérent avec le nom de l'autre méthode, pourquoi ne pas nommer cette méthode createSlaveReader

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +    List<String> unregisterVirtualReaders = new ArrayList<String>(2);
Non, juste true si le maître n'a pas d'observers ou si ce n'est pas un observable

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +    if (!(virtualReader instanceof RemoteSeServerObservableReader)) {
Ce passage pourrait être plus simple...

2020-09-10 13:48 UTC, andrei-cristea commented on java/component/keyple-plugin/remote-se/virtualse/src/main/java/org/eclipse/keyple/plugin/remotese/virtualse/impl/RemoteSeServerPluginImpl.java
> +    ServerVirtualObservableReader virtualObservableReader =
nommer plutôt master

2020-09-14 09:15 UTC, odelcroi commented
retest this please

2020-09-14 11:59 UTC, andrei-cristea approved these changes

2020-09-14 12:31 UTC, merged