Feat/keyp 272 build examples
eclipse/keyple-java pull request #423
Opened 2020-10-08 13:59 UTC by odelcroi

- Build webservice example based on Quarkus

- Build websocket example based on Quarkus

2020-10-09 09:04 UTC, andrei-cristea requested changes

2020-10-12 08:05 UTC, odelcroi commented on java/component/keyple-plugin/remote-se/example/common/src/main/java/org/eclipse/keyple/remotese/example/app/RemoteSePluginObserver.java
> +      UserInfo userInput = virtualReader.getUserInputData(UserInfo.class);
ok

2020-10-12 08:06 UTC, odelcroi commented on java/component/keyple-plugin/remote-se/example/keyple-example-remotese-web-service/gradlew
> +#!/usr/bin/env sh
yes, it is advised to commit the gradle wrapper

2020-10-12 08:06 UTC, odelcroi commented on java/component/keyple-plugin/remote-se/example/keyple-example-remotese-web-service/gradlew.bat
> +@rem
yes, it is advised to commit the gradle wrapper

2020-10-12 08:06 UTC, odelcroi commented on java/component/keyple-plugin/remote-se/example/common/src/main/java/org/eclipse/keyple/remotese/example/app/RemoteSePluginObserver.java
> +        // retrieve serviceId from reader
ok

2020-10-12 08:06 UTC, odelcroi commented on java/component/keyple-plugin/remote-se/example/common/src/main/java/org/eclipse/keyple/remotese/example/app/RemoteSePluginObserver.java
> +      UserInfo userInput = virtualReader.getUserInputData(UserInfo.class);
ok

2020-10-12 12:27 UTC, andrei-cristea approved these changes

2020-10-12 12:28 UTC, merged