Feat/keyp 275 remote pool client plugin
eclipse/keyple-java pull request #434
Opened 2020-11-02 10:55 UTC by odelcroi

Add Remote Pool Client Plugin

2020-11-02 15:07 UTC, andrei-cristea requested changes

2020-11-02 15:07 UTC, andrei-cristea commented on java/component/keyple-plugin/remote/virtual/src/main/java/org/eclipse/keyple/plugin/remote/virtual/impl/RemotePoolClientPluginImpl.java
> +      readers.remove(reader.getName());
Je pense qu'il faut retirer le reader dès le début, avant d'envoyer la requête au serveur.

2020-11-02 15:07 UTC, andrei-cristea commented on java/component/keyple-plugin/remote/virtual/src/main/java/org/eclipse/keyple/plugin/remote/virtual/impl/RemotePoolClientPluginImpl.java
> +    return new ConcurrentHashMap<String, SeReader>();
A t-on réellement besoin d'une ConcurrentHashMap ?

2020-11-02 15:07 UTC, andrei-cristea commented on java/component/keyple-plugin/remote/virtual/src/main/java/org/eclipse/keyple/plugin/remote/virtual/impl/RemotePoolClientUtils.java
> +  public static KeypleClientSyncNode getSyncNode() {
Supprimer cette méthode.

2020-11-03 08:57 UTC, andrei-cristea approved these changes

2020-11-03 09:18 UTC, brice-ruppen commented on java/component/keyple-plugin/remote/virtual/src/main/java/org/eclipse/keyple/plugin/remote/virtual/impl/RemotePoolClientUtils.java
> +  public static KeypleClientSyncNode getSyncNode() {
Du coup ya le commentaire qui va pas bien sur cette méthode et qui fait douter de son utilité :
RemotePoolClientPluginFactory.withSyncNode(KeypleClientSync syncEndpoint)

2020-11-03 16:48 UTC, merged